### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by jibby0** [jibby0/IGME582-final#1]
@erway1998 will create assets.

Development can continue with dummy assets for now, as we need them. Be sure to use CC-licensed (or otherwise) dummy assets.

**Comment by jibby0** [comment]
@erway1998 wanna push assets as you have them? Maybe into an assets branch?

**Comment by jibby0** [comment]
Do we want a different background, or bottom bar?

**Comment by pyrophone** [comment]
I think it's alright to have the background and bottom bar the way they are, but it might be preferable to make / get a different space background that has more stars at least. I wouldn't say it's super important though

**Comment by jibby0** [comment]
I agree, our bar works well enough for what it is, and a different background would be less distracting than our current Saturn. @erway1998 thoughts or proposals?

**Comment by greengazebo** [comment]
I feel like anything other than a stary sky would be distracting in the
same way. So probably just that.

**Comment by jibby0** [comment]
Alrighty. I'll find a suitable background.
